# @package _global_

defaults:
  - _base_dataset@_here_
  - _self_

name: 'chat'
bad_recordings: [ 'baseline-300927', 'baseline-300051' ]  # https://sleepdata.org/datasets/chat/pages/polysomnography-introduction.md

psg:
  file_glob: 'chat/polysomnography/edfs/*/*.edf'
  eeg_channels: [ 'F3-M2', 'F4-M1', 'C3-M2', 'C4-M1', 'T3-M2', 'T4-M1', 'O1-M2', 'O2-M1' ]
  eog_channels: [ 'E1-M2', 'E2-M1' ]
  emg_channels: [ 'LCHIN-CCHIN', 'RCHIN-CCHIN' ]
  renamed_emg_channels: [ 'EMGl', 'EMGr' ]
  id_regex: ".*-(.*-.*)"

hypno:
  file_glob: 'chat/polysomnography/annotations-events-nsrr/*/*.xml'
  id_regex: ".*-(.*-.*)-.*"

splitting:
  subject_id_regex: "-(.*)"
